[package]
name = "rust-parallel-scans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
iterx = "0.0.4"
rust-tx = { path = "../rust-tx" }
